language: python
python:
  - "2.7"
cache: pip
install: pip install -r requirements.txt
script: 
  - python StackIt.py StressTest1.dec
  - python StackIt.py "Elf Stompy.dek"
  - python StackIt.py StressTest1.dec
