language: python
python:
  - "2.7"
cache: pip
install: pip install -r requirements.txt
script: 
  - find testdecks/ -name "*.txt" | xargs python StackIt.py
  - find testdecks/ -name "*.dec" | xargs python StackIt.py
  - find testdecks/ -name "*.dek" | xargs python StackIt.py
