language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install: pip install -r requirements.txt
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - find testdecks/ -name "*.txt" -print0 | xargs -0 python StackIt.py
  - find testdecks/ -name "*.dec" -print0 | xargs -0 python StackIt.py
  - find testdecks/ -name "*.dek" -print0 | xargs -0 python StackIt.py
  - python GUIapp.py --automatedtest
