language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install: pip install -r requirements.txt
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - python StackIt/StackIt.py --automatedtest
  - python StackIt/GUIapp.py --automatedtest
